name: Aite Studio Builder

on:
  workflow_dispatch: # تشغيل يدوي من الزر في المحرر
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # التحقق مما إذا كان المشروع موجوداً
      - name: Check & Init Project
        id: init
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "No project found. Creating new Flutter project..."
            flutter create --platforms=android,web --project-name=aite_app .
            
            # إعداد هوية جيت للرفع
            git config --global user.name "Aite Studio Bot"
            git config --global user.email "bot@aite.studio"
            
            # إضافة الملفات ورفعها للمستودع حتى تظهر في المحرر لديك
            git add .
            git commit -m "Initialize Flutter Project by Aite.studio"
            git push
          else
            echo "Project found. Proceeding to build..."
          fi

      # بناء نسخة الويب
      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      # نشر الويب
      - name: Deploy Web to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      # بناء نسخة الأندرويد
      - name: Build Android APK
        run: flutter build apk --release

      # رفع APK للتحميل
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
